In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/raw/predictive_maintenance.csv")

df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Target,Failure Type
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,No Failure
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,No Failure
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,No Failure
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,No Failure
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,No Failure

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   UDI                      10000 non-null  int64
 1   Product ID               10000 non-null  str
 2   Type                     10000 non-null  str
 3   Air temperature [K]      10000 non-null  float64
 4   Process temperature [K]  10000 non-null  float64
 5   Rotational speed [rpm]   10000 non-null  int64
 6   Torque [Nm]              10000 non-null  float64
 7   Tool wear [min]          10000 non-null  int64
 8   Target                   10000 non-null  int64
 9   Failure Type             10000 non-null  str
dtypes: float64(3), int64(4), str(3)
memory usage: 781.4 KB

In [4]:
df = df.drop(columns=[
    "UDI",
    "Product ID",
    "Failure Type"
])

df.head()

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Target
0,M,298.1,308.6,1551,42.8,0,0
1,L,298.2,308.7,1408,46.3,3,0
2,L,298.1,308.5,1498,49.4,5,0
3,L,298.2,308.6,1433,39.5,7,0
4,L,298.2,308.7,1408,40.0,9,0

In [5]:
df["Type"].value_counts()

Type
L    6000
M    2997
H    1003
Name: count, dtype: int64

In [6]:
df["Type"] = df["Type"].map({
    "L": 0,
    "M": 1,
    "H": 2
})

In [7]:
X = df.drop(columns=["Target"])

y = df["Target"]

In [8]:
print("X:", X.shape)
print("y:", y.shape)

X: (10000, 6)
y: (10000,)

In [9]:
X.head()

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min]
0,1,298.1,308.6,1551,42.8,0
1,0,298.2,308.7,1408,46.3,3
2,0,298.1,308.5,1498,49.4,5
3,0,298.2,308.6,1433,39.5,7
4,0,298.2,308.7,1408,40.0,9

In [10]:
X_normalizado = (X - X.min()) / (X.max() - X.min())

In [11]:
X_normalizado.describe()

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min]
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,0.25015,0.511405,0.531551,0.215818,0.497073,0.426684
std,0.33565,0.217419,0.183177,0.104356,0.136936,0.251597
min,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.00000,0.326087,0.382716,0.148428,0.403846,0.209486
50%,0.00000,0.521739,0.543210,0.194994,0.498626,0.426877
75%,0.50000,0.673913,0.666667,0.258440,0.590659,0.640316
max,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000

In [12]:
X = X_normalizado.to_numpy()

y = y.to_numpy()

In [13]:
print(X.shape)
print(y.shape)

(10000, 6)
(10000,)